### PR TITLE
44102 Tao và validate: Address, Payment, Contributes

### PR DESCRIPTION
**Pull request by hieuvc-2823**
## Related Tickets
- [#44102](https://edu-redmine.sun-asterisk.vn/issues/44102)

## WHAT (optional)
--Tạo Model: Address, Payment, Contributes
--Vaidate models
--Tạo associations

## Evidence (Screenshot or Video)
Screenshot from 2021-12-10 16-32-51

### CODE REVIEW

**Comment by hieuvc-2823** [comment]
ready

**Comment by hieuvc-2823** [comment]
Screenshot from 2021-12-10 16-58-58

**Comment by hieuvc-2823** [comment]
ready

**Comment by hieuvc-2823** [comment]
ready

**Comment by hieuvc-2823** [comment]
Screenshot from 2021-12-14 17-28-05

**Comment by hieuvc-2823** [comment]
ready

**Review by ghost — APPROVED** [review]

**Pull request merged**
